version: "3.3"
services:
  loadbalancer:
    container_name: reliabank-loadbalancer
    image: sanjivkannaajeganathan/chaosbank:v1_loadbalancer
    # build:
    #   context: .
    #   dockerfile: Dockerfile.loadbalancer
    restart: always
    ports:
      - "80:80"
    networks:
      - reliabank-network
  frontend:
    container_name: reliabank-frontend
    image: sanjivkannaajeganathan/chaosbank:v1_frontend
    # build:
    #   context: ../../frontend/
    #   dockerfile: Dockerfile.frontend
    restart: always
    # volumes:
    #   - ../../frontend:/app
    ports:
      - "3000:3000"
    networks:
      - reliabank-network
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    command: sh -c "npm start"
  backend:
    container_name: reliabank-webserver
    image: sanjivkannaajeganathan/chaosbank:v1_backend
    # build:
    #   context: ../../backend/
    #   dockerfile: Dockerfile.backend
    restart: always
    volumes:
      - ../../backend:/app
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - reliabank-network
    command: ["python3", "main.py"]
  mysql:
    image: mysql:8.0
    container_name: reliabank-mysql
    restart: always
    env_file: ../../backend/.env
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - reliabank-network
    ports:
      - "3306:3306"
networks:
  reliabank-network:
    driver: bridge
volumes:
  mysql:
