version: "3.3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    networks:
      - reliabank-network
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true # Fixes issues with live reloading in some environments
    command: sh -c "npm start"
  backend:
    container_name: reliabank-webserver
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    restart: always
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - reliabank-network
    command: ["python3", "main.py"]
  mysql:
    image: mysql:8.0
    container_name: reliabank-mysql
    restart: always
    env_file: ./backend/.env
    command: --server-id=1
    volumes:
      - master_data:/var/lib/mysql
    networks:
      - reliabank-network
    ports:
      - "3306:3306"

  mysql-slave1:
    image: mysql:8.0
    container_name: reliabank-mysql-slave1
    restart: always
    env_file: ./backend/.env
    command: --server-id=2 --read-only=1
    volumes:
      - slave1_data:/var/lib/mysql
    networks:
      - reliabank-network

  mysql-slave2:
    image: mysql:8.0
    container_name: reliabank-mysql-slave2
    restart: always
    env_file: ./backend/.env
    command: --server-id=3 --read-only=1
    volumes:
      - slave2_data:/var/lib/mysql
    networks:
      - reliabank-network
networks:
  reliabank-network:
    driver: bridge
volumes:
  master_data:
  slave1_data:
  slave2_data:
