FROM python:3.8-slim
WORKDIR /app
RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get install -y --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*
RUN pip install --upgrade pip
COPY init.py .
RUN python init.py
