version: "3.3"
services:
  web-server:
    container_name: reliabank-webserver
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./:/app
    ports:
      - "${port}:5000"
    depends_on:
      - db
    networks:
      - reliabank-network
    command: ["python3", "main.py"]
  db:
    container_name: reliabank-db
    image: mongo
    expose: 
      - 27017
    volumes:
      - mongodbdata:/data/db
    networks:
      - reliabank-network
    
networks:
  reliabank-network:
    driver: bridge
volumes:
  mongodbdata:
