version: "3.3"
services:
  web-server:
    container_name: reliabank-webserver
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: always
    volumes:
      - ./:/app
    ports:
      - "${port}:5000"
    command: ["python3", "main.py"]
    networks:
      - backend_mysql_net

networks:
  backend_mysql_net:
    external: true
