- hosts: reliabank1
  become: yes
  tasks:
    - name: Change directory and bring down Docker Compose services
      shell: |
        cd /home/admin/reliabank
        docker-compose --env-file=.env.example down
      args:
        chdir: /home/admin/reliabank

    - name: Prune all Docker system resources
      command: docker system prune --all -f

    - name: Remove the repository directory
      file:
        path: /home/admin/reliabank
        state: absent

- hosts: reliabank2
  become: yes
  tasks:
    - name: Change directory and bring down Docker Compose services
      shell: |
        cd /home/admin/reliabank
        docker-compose --env-file=.env.example down
      args:
        chdir: /home/admin/reliabank

    - name: Prune all Docker system resources
      command: docker system prune --all -f

    - name: Remove the repository directory
      file:
        path: /home/admin/reliabank
        state: absent

