CHANGE REPLICATION SOURCE TO
    SOURCE_HOST='mysql',
    SOURCE_USER='reliabank',
    SOURCE_PASSWORD='reliabank',
    SOURCE_LOG_FILE='binlog.000002',
    SOURCE_LOG_POS=1684;
    GET_MASTER_PUBLIC_KEY=1;
    -- SOURCE_AUTO_POSITION=1;
START REPLICA;

SHOW REPLICA STATUS;
